import Link from 'next/link';
import LaserBackdrop from '@/components/LaserBackdrop';
import ProjectCover from '@/components/ProjectCover';

/**
 * Home page — kylerauch.com (M4 Modern Archetype redesign)
 *
 * Structure:
 *   1. Editorial hero — eyebrow + serif headline (with italic emphasis)
 *      + body + dual CTA. Right column: headshot in glass-card with
 *      rust-tinted backdrop blob.
 *   2. WebGL lasers retinted to rust (color={[0.7, 0.33, 0.12]} = #b3541e
 *      brand-container). Lower opacity than before since editorial design
 *      prioritizes content over motion.
 *   3. Selected Works — 12-col bento grid:
 *        Row 1: hero project (8-col) + small (4-col)
 *        Row 2: small (4-col) + hero project (8-col)
 *      Hero projects = OfferPilotV2, support-triage, csm-account-pulse,
 *      diamond-edge.
 *   4. Capabilities — 3-col with eyebrow labels and short descriptions.
 *
 * Image placeholders: /headshot.jpg + /projects/<slug>/cover.jpg.
 * Kyle drops the headshot in public/ separately; project covers are AI-
 * generated by Kyle into public/projects/<slug>/cover.jpg.
 */

const HERO_PROJECTS = [
  {
    slug: 'offerpilot-v2',
    name: 'OfferPilotV2',
    blurb:
      'Desktop-first, local-first job-search command center. Multi-agent pipeline with Scout / Tailor / Researcher subagents and human-in-the-loop approval.',
    tags: ['Tauri', 'Rust', 'React'],
    size: 'large' as const,
  },
  {
    slug: 'support-triage',
    name: 'Support Triage',
    blurb:
      'Local-first AI triage for B2B SaaS support — classify, retrieve KB, draft citation-grounded replies, suggest macros. Eval-driven.',
    tags: ['Python', 'Evals'],
    size: 'small' as const,
  },
  {
    slug: 'csm-account-pulse',
    name: 'CSM Account Pulse',
    blurb:
      'Single-page Streamlit dashboard a CSM opens every Monday. Documented v1→v5 prompt iteration with held-out scenarios.',
    tags: ['Python', 'Streamlit'],
    size: 'small' as const,
  },
  {
    slug: 'diamond-edge',
    name: 'Diamond Edge',
    blurb:
      'MLB pick recommendation system — gradient-boosted models plus grounded LLM rationale plus two parallel Claude agent pipelines.',
    tags: ['TypeScript', 'Python', 'Claude SDK'],
    size: 'large' as const,
  },
];

export default function Home() {
  return (
    <main className="min-h-screen pt-24">
      {/* HERO */}
      <section className="relative overflow-hidden">
        <LaserBackdrop opacity={60} />

        <div className="relative z-10 max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop pt-20 pb-section-gap grid grid-cols-1 md:grid-cols-12 gap-gutter items-center">
          {/* Left column — copy */}
          <div className="md:col-span-7">
            <span className="font-sans text-label-caps font-semibold text-primary mb-6 block uppercase tracking-[0.2em]">
              L2 SaaS escalation operator · AI-tooling builder
            </span>
            <h1 className="font-serif text-[44px] md:text-[64px] lg:text-display text-on-surface leading-[1.05] mb-8">
              I direct.{' '}
              <span className="italic text-primary">AI</span>{' '}
              implements.
            </h1>
            <p className="font-sans text-body-lg text-on-surface-variant mb-10 max-w-[540px]">
              Years in the L2 queue at AI-forward SaaS — sustained exposure to
              where customers hit walls. I build the local-first tools support,
              CS, and SE teams actually need, eval-driven and shipped.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                href="/projects"
                className="bg-primary-container text-on-primary-container font-sans text-label-caps font-semibold px-10 py-5 rounded uppercase tracking-widest hover:brightness-110 transition-all"
              >
                View my work
              </Link>
              <Link
                href="/about"
                className="border border-outline text-on-surface font-sans text-label-caps font-semibold px-10 py-5 rounded uppercase tracking-widest hover:bg-surface-container-low transition-all"
              >
                About me
              </Link>
            </div>
          </div>

          {/* Right column — headshot in glass card with rust glow */}
          <div className="hidden md:block md:col-span-5 relative">
            <div className="aspect-[4/5] rounded-xl overflow-hidden glass-card p-4">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/Headshot.webp"
                alt="Portrait of Kyle Rauch"
                className="w-full h-full object-cover rounded-lg transition-all duration-700 hover:scale-[1.02]"
              />
            </div>
            {/* Rust-tinted backdrop blob */}
            <div
              className="absolute -z-10 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[140%] h-[140%] rounded-full blur-[100px]"
              style={{ background: 'rgba(179, 84, 30, 0.08)' }}
              aria-hidden="true"
            />
          </div>
        </div>
      </section>

      {/* SELECTED WORKS — bento grid */}
      <section className="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-section-gap">
        <div className="flex justify-between items-end mb-16">
          <div>
            <h2 className="font-serif text-headline-lg text-on-surface mb-4">
              Selected Works
            </h2>
            <div className="h-1 w-24 bg-primary" />
          </div>
          <Link
            href="/projects"
            className="hidden md:inline-block font-sans text-label-caps font-semibold text-on-surface-variant hover:text-primary transition-colors uppercase tracking-widest"
          >
            View all projects →
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-12 gap-8">
          {HERO_PROJECTS.map((project) => (
            <Link
              key={project.slug}
              href={`/projects/${project.slug}`}
              className={
                project.size === 'large'
                  ? 'md:col-span-8 group'
                  : 'md:col-span-4 group'
              }
            >
              <article className="glass-card rounded-xl overflow-hidden rust-glow transition-all duration-500 h-full flex flex-col">
                <div
                  className={
                    project.size === 'large'
                      ? 'aspect-video overflow-hidden bg-surface-container-low'
                      : 'aspect-[4/5] overflow-hidden bg-surface-container-low'
                  }
                >
                  <ProjectCover
                    src={`/projects/${project.slug}/cover.jpg`}
                    alt={`${project.name} cover`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                </div>
                <div className="p-8 flex-1 flex flex-col">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <h3 className="font-serif text-headline-md text-on-surface mb-3">
                        {project.name}
                      </h3>
                      <div className="flex flex-wrap gap-2">
                        {project.tags.map((tag) => (
                          <span
                            key={tag}
                            className="font-sans text-[10px] font-semibold px-3 py-1 bg-outline-variant/20 rounded-full text-on-surface-variant uppercase tracking-wider"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                    <span className="text-primary group-hover:translate-x-2 transition-transform text-xl leading-none">
                      ↗
                    </span>
                  </div>
                  <p className="font-sans text-body-md text-on-surface-variant">
                    {project.blurb}
                  </p>
                </div>
              </article>
            </Link>
          ))}
        </div>
      </section>

      {/* CAPABILITIES */}
      <section className="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-section-gap">
        <div className="text-center max-w-[800px] mx-auto mb-20">
          <h2 className="font-serif text-headline-lg text-on-surface mb-6">
            Operator, builder, escalation engineer.
          </h2>
          <p className="font-sans text-body-lg text-on-surface-variant">
            Customer-facing rigor combined with the engineering instinct to ship
            AI features that actually work — not demos, not slideware.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-gutter">
          <div className="p-8 border-l border-outline-variant/20 hover:border-primary transition-colors group">
            <p className="font-sans text-label-caps font-semibold text-primary mb-6 uppercase tracking-widest">
              Customer trenches
            </p>
            <h4 className="font-serif text-[24px] text-on-surface mb-4">
              Years in the L2 queue
            </h4>
            <p className="font-sans text-body-md text-on-surface-variant">
              Sustained exposure to where customers hit walls at AI-forward
              SaaS. I know what breaks because I&apos;ve worked the queue,
              not because I read the support docs.
            </p>
          </div>
          <div className="p-8 border-l border-outline-variant/20 hover:border-primary transition-colors group">
            <p className="font-sans text-label-caps font-semibold text-primary mb-6 uppercase tracking-widest">
              AI tooling
            </p>
            <h4 className="font-serif text-[24px] text-on-surface mb-4">
              I direct, AI implements
            </h4>
            <p className="font-sans text-body-md text-on-surface-variant">
              Local-first agentic pipelines, multi-LLM provider abstractions,
              eval-driven prompt iteration. Tools I&apos;ve shipped:
              triage, sourcing, account pulse, job-search orchestration.
            </p>
          </div>
          <div className="p-8 border-l border-outline-variant/20 hover:border-primary transition-colors group">
            <p className="font-sans text-label-caps font-semibold text-primary mb-6 uppercase tracking-widest">
              Solutions engineering
            </p>
            <h4 className="font-serif text-[24px] text-on-surface mb-4">
              From queue to architecture
            </h4>
            <p className="font-sans text-body-md text-on-surface-variant">
              Comfortable across the stack — Rust, TypeScript, Python, SQL.
              Security+ certified. FINRA 7/63 (lapsed) for financial-services
              context.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
